### ISSUE TITLE
svg:not(:root) breaks pretty hard.

### ISSUE THREAD

**Issue by SlexAxton** [SlexAxton/rework-pseudo-classes#5]
```css
svg:not(:root),
svg.bs-pseudo-root--:not(,
svg.bs-pseudo-not--:root),
svg.bs-pseudo-root--.bs-pseudo-not-- {
  overflow: hidden;
}
```
